version: '3'

services:
  laravel-app:
    container_name: laravel-app
    build: .
    volumes:
      - ./src/:/var/www/html
    ports:
      - 9000:80
  
  mysql_db:
    container_name: mysql_db
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pms_project_db
    ports:
      - 3306:3306

  mysql_db_testing:
    container_name: mysql_db_testing
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pms_project_db
    ports:
      - 3307:3306
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1